# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(602, 450)
        self.Button_2 = QtWidgets.QPushButton(Form)
        self.Button_2.setGeometry(QtCore.QRect(210, 310, 191, 91))
        self.Button_2.setObjectName("Button_2")
        self.Screen_2 = QtWidgets.QTextEdit(Form)
        self.Screen_2.setGeometry(QtCore.QRect(60, 30, 501, 241))
        self.Screen_2.setObjectName("Screen_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button_2.setText(_translate("Form", "Button_2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
